# Generated by Django 2.1 on 2021-12-14 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='User',
            new_name='username',
        ),
    ]
